"""m2 validation routing review

Revision ID: 7739ec01fc81
Revises: 208f614d36f0
Create Date: 2026-10-06 12:33:32.235811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7739ec01fc81'
down_revision: Union[str, Sequence[str], None] = '208f614d36f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('approve', 'edit', 'reject', name='review_action'), nullable=False),
    sa.Column('field_edits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_invoice_id'), 'review_decisions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_tenant_id'), 'review_decisions', ['tenant_id'], unique=False)
    op.add_column('invoices', sa.Column('extraction_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('validation_issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoices', sa.Column('route', sa.String(length=30), nullable=True))
    op.add_column('invoices', sa.Column('route_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'route_reasons')
    op.drop_column('invoices', 'route')
    op.drop_column('invoices', 'validation_issues')
    op.drop_column('invoices', 'extraction_attempts')
    op.drop_index(op.f('ix_review_decisions_tenant_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_invoice_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.execute('DROP TYPE IF EXISTS review_action')
    # ### end Alembic commands ###
