"""nullable line tax rate

Revision ID: e1f78113cc08
Revises: d9a3fb32825e
Create Date: 2026-10-06 13:50:12.803801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f78113cc08'
down_revision: Union[str, Sequence[str], None] = 'd9a3fb32825e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_lines', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_lines', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    # ### end Alembic commands ###
